### PR TITLE
Streams Table

### LINKED ISSUE #24: Strams table
According to our [db specification](https://github.com/beyond-io/sellotape#technological-stack), set up the `streams` db table.

### PR DESCRIPTION
**Pull request by alonweissfeld**
Resolves #24.

Basic implementation of the `streams` table to support querying previous and scheduled streams of users.
Note that the implementation of our database tables is split to different tasks and therefore the `User` Model will be expanded as part of #23.

### CODE REVIEW

**Review by ifireball — CHANGES_REQUESTED** [review]
Since all the commits you have here come down to a rather small set of changes, consider squashing them together with `git rebase -i`.

I'm seeing a new Model class but now a new migration file - generally when you add or change model classes you need to generate the migration files for the change and commit them to Git as well.

**Review by ifireball — APPROVED** [review]
Code LGTM - I still prefer it if you squash all the commits to a single one because this is in total a rather small change

**Comment by alonweissfeld** [comment]
@ifireball Done.

**Comment by alonweissfeld** [comment]
@ifireball This PR is approved and all comments were fixed. As discussed today in Zoom, I'm merging.

**Pull request merged**
