### PR TITLE
intagrate - chat by stream

### LINKED ISSUE #73: Integrate the ChatApp inside LIVE and Future Streams
When a stream is live (or a future stream is not yet live)
Users should be able to chat in the stream's room

This needs to happen AFTER the chatapp is fully BootStrap'ed

### PR DESCRIPTION
**Pull request by rosomri**
Solve #73 

- integrate the chat inside each stream.

- the integration based on the stream's pk (unique).

- by clicking the "Talk About!" button - you move on to the unique chat (Pictures attached)
landing-page

user-page

chat-page

### CODE REVIEW

**Review by alonweissfeld — APPROVED** [review]
LGTM

**Comment by ItzhakiGuy** [comment]
Looks great, something was broken in the testing of the CI, I think it is the testing of the templates.

**Review by ItzhakiGuy — APPROVED** [review]

**Comment by rosomri** [comment]
> Looks great, something was broken in the testing of the CI, I think it is the testing of the templates.

@itzhaki1234 
Take a look again ;)

**Comment by ItzhakiGuy** [comment]
Excellent!!! ;-)

**Pull request merged**
